  apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name}}-fluentbit
  labels: {{ include "logging.labels" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name}}-fluentbit
  labels: {{ include "logging.labels" . | indent 4 }}
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name}}-fluentbit
  labels: {{ include "logging.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name}}-fluentbit
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name}}-fluentbit
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name}}-fluentbit-init
  labels: {{ include "logging.labels" . | indent 4 }}
rules:
- apiGroups: ["batch"]
  resources:
  - jobs
  - jobs/status
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name}}-fluentbit-init
  labels: {{ include "logging.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name}}-fluentbit-init
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name}}-fluentbit
  namespace: {{ .Release.Namespace }}