{{- if .Values.kafka.enabled }}        
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name}}-fluentd
  labels: {{ include "logging.labels" . | indent 4 }}
    k8s-app: fluend    
spec:
  replicas: {{ .Values.fluentd.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      k8s-app: fluentd
  template:
    metadata:
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        k8s-app: fluentd        
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluentd/fluentd-config.yaml") . | sha256sum }}          
    spec:
      priorityClassName: {{ default .Values.priority_class .Values.fluentd.priority_class }}
      serviceAccountName: {{ .Release.Name}}-fluentd      
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      {{- with .Values.fluentd.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }} 
      {{- end }}
      initContainers:
      - name: init
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        image: {{ include "init_container.image" . }}
        command: ["sh","-c",'/init/check_os.sh && /init/check_host_port.sh $kafka 9092']
        env:
          - name: os_url
            value: {{ include "os_url" . }}
          - name: os_user
            value: {{ .Values.opensearch.user }}
          - name: os_pass
            value: {{ .Values.opensearch.password }}
          - name: kafka
            value: {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}  
        volumeMounts:
        - mountPath: "/init"
          name: init      
      containers:
      - name: fluentd
        imagePullPolicy: {{ .Values.fluentd.imagePullPolicy }}      
        image: {{ .Values.fluentd.image }}:{{ .Values.fluentd.imageTag }}       
        resources: {{ toYaml .Values.fluentd.resources | nindent 10 }}
        command:
        - "/bin/sh"
        - "-c"
        - "/fluentd/entrypoint.sh"
        env:
        - name: FLUENT_OPENSEARCH_HOST
          value: "{{ include "os_host" . }}"
        - name: FLUENT_OPENSEARCH_PORT
          value: "{{ include "os_port" . }}"
        - name: FLUENT_OPENSEARCH_USER
          value:  {{ .Values.opensearch.user }}
        - name: FLUENT_OPENSEARCH_PASSWORD
          value:  {{ .Values.opensearch.password }}
        {{- if .Values.fluentd.extraEnvs }}
          {{- toYaml .Values.fluentd.extraEnvs | nindent 8 }}
        {{- end }}
        startupProbe:        
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 60
          periodSeconds: 60          
        ports:
        - name: metrics
          containerPort: 24231
          protocol: TCP    
        volumeMounts:
        - name: fluentd-buffer
          mountPath: /fluentd/buffer
        - name: fluentd-config        
          mountPath: /fluentd/etc
        - name: certificates
          mountPath: /fluentd/ssl/root-ca.pem
          subPath: root-ca.pem
        - name: certificates
          mountPath: /fluentd/ssl/admin.pem
          subPath: admin.pem  
        - name: certificates
          mountPath: /fluentd/ssl/admin-key.pem
          subPath: admin-key.pem    
        - name: index-templates
          mountPath: /fluentd/templates         
      terminationGracePeriodSeconds: 10
      volumes:
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755  
      - name: fluentd-buffer
        emptyDir: {}
      - name: fluentd-config
        configMap:
          name: {{ .Release.Name}}-fluentd          
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-certificates  
      - name: index-templates
        configMap:
          name: {{ .Release.Name}}-index-templates      
      {{- with .Values.fluentd.affinity }}     
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fluentd.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}      
