{{- if .Values.fluentbit.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Release.Name }}-fluent-bit
  labels: {{ include "logging.selectorLabels" . | indent 4 }}
    k8s-app: fluent-bit
spec:
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      k8s-app: fluent-bit
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/fluent-bit/fluent-bit-config-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        k8s-app: fluent-bit
        {{- with .Values.fluentbit.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: {{ default .Values.priorityClass .Values.fluentbit.priorityClass }}
      securityContext:
        runAsUser: 0
      serviceAccountName: {{ .Release.Name }}-fluent-bit
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: check-os
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        image: {{ include "init_container.image" . }}
        command: ["sh","-c",'/init/check_os.sh']
        env:
          - name: os_url
            value: {{ include "os_url" . }}
          - name: os_user
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-opensearch-credentials-admin
                key: username
          - name: os_pass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-opensearch-credentials-admin
                key: password
        volumeMounts:
        - name: certificates
          mountPath: /ssl/root-ca.pem
          subPath: ca.crt
        - mountPath: "/init"
          name: init
      {{- if .Values.kafka.enabled }}
      - name: check-kafka
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        image: {{ include "init_container.image" . }}
        command: ["sh","-c",'/init/check_host_port.sh $kafka 9092']
        env:
          - name: kafka
            value: {{ .Release.Name }}-kafka-{{ (sub (.Values.kafka.replicas | int) 1) }}
        volumeMounts:
        - mountPath: "/init"
          name: init
      {{- end }}
      {{- if .Values.opensearch.externalOpensearch.disabled }}
      - name: check-job
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        image: {{ include "init_container.image" . }}
        command: ["sh","-c",'/init/check_job.sh']
        env:
          - name: job_name
            value: {{ .Release.Name }}-index-templates
          - name: job_namespace
            value: {{ .Release.Namespace }}
        volumeMounts:
        - mountPath: "/init"
          name: init
      {{- end }}
      containers:
      - name: fluent-bit
        image: {{ .Values.fluentbit.image }}:{{ .Values.fluentbit.imageTag }}
        imagePullPolicy: {{ .Values.fluentbit.imagePullPolicy }}
        resources: {{ toYaml .Values.fluentbit.resources | nindent 10 }}
        ports:
          - name: http
            containerPort: 2020
          - name: cfgw
            containerPort: 8888
        env:
        - name: FLUENT_opensearch_HOST
          value: "{{ include "os_host" . }}"
        - name: FLUENT_opensearch_PORT
          value: "{{ include "os_port" . }}"
        - name: FLUENT_opensearch_USER
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: username
        - name: FLUENT_opensearch_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: password
        {{- if .Values.fluentbit.extraEnvs }}
          {{- toYaml .Values.fluentbit.extraEnvs | nindent 8 }}
        {{- end }}
        livenessProbe:
          httpGet:
            path: /api/v1/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 15
        volumeMounts:
        - name: fluentbitstate
          mountPath: /var/fluent-bit/state
        - name: containerslog
          mountPath: /var/log/pods
          readOnly: true
        {{- if .Values.fluentbit.containersRuntime }}
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
        {{- end }}
        - name: journallog
          mountPath: /run/log
          readOnly: true
        - name: fluent-bit-config
          mountPath: /fluent-bit/etc
        {{- if or .Values.fluentbit.caCertificateSecret .Values.opensearch.externalOpensearch.disabled }}
        - name: certificates
          mountPath: /fluent-bit/ssl/root-ca.pem
          subPath: ca.crt
        {{- end }}
        - name: admin-certificate
          mountPath: /fluent-bit/ssl/admin.pem
          subPath: tls.crt
        - name: admin-certificate
          mountPath: /fluent-bit/ssl/admin-key.pem
          subPath: tls.key
      terminationGracePeriodSeconds: 10
      volumes:
      - name: fluentbitstate
        hostPath:
          path: /var/fluent-bit/state
      - name: init
        configMap:
          name: {{ .Release.Name }}-init
          defaultMode: 0755
      - name: journallog
        hostPath:
          path: {{ .Values.fluentbit.journalsLogsHostPath }}
      - name: containerslog
        hostPath:
          path: {{ .Values.fluentbit.containersLogsHostPath }}
      {{- if .Values.fluentbit.containersRuntime }}
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      {{- end }}
      - name: fluent-bit-config
        secret:
          secretName: {{ .Release.Name }}-fluent-bit
      - name: certificates
        secret:
          {{- if .Values.fluentbit.caCertificateSecret }}
          secretName: {{ .Values.fluentbit.caCertificateSecret }}
          {{- else }}
          secretName: {{ .Release.Name }}-opensearch-certificates
          {{- end }}
      - name: admin-certificate
        secret:
          secretName: {{ .Release.Name }}-opensearch-admin-certificate
      {{- with .Values.fluentbit.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fluentbit.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
