apiVersion: batch/v1
kind: Job
metadata:  
  labels:
    app: logger
  name: logger
spec:
  completions: 10
  completionMode: "Indexed"
  ttlSecondsAfterFinished: 100
  parallelism: 2
  template:
    metadata:      
      labels:
        app: logger        
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: logger
      restartPolicy: Never  
      containers:
      - image: nickytd/log-generator
        name: log-generator
        args:
          - -wait 
          - "-1"
          - -count 
          - "100000"
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 1000m
