{{- if and (.Values.data_prepper) ( .Values.data_prepper.enabled) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-data-prepper
  labels: {{ include "logging.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.data_prepper.replicas }}
  selector:
    matchLabels: {{ include "logging.selectorLabels" . | indent 6 }}
      type: data-prepper
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opensearch/os-data-prepper-configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/opensearch/os-data-prepper-sec.yaml") . | sha256sum }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: data-prepper
        {{- with .Values.data_prepper.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: {{ default .Values.priorityClass .Values.data_prepper.priorityClass }}
      {{- with .Values.data_prepper.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.data_prepper.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.data_prepper.topologySpreadConstraints }}
      topologySpreadConstraints: {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: main
        image: {{ .Values.data_prepper.image }}:{{ .Values.data_prepper.imageTag }}
        imagePullPolicy: {{ .Values.opensearch.imagePullPolicy }}
        resources: {{ toYaml .Values.data_prepper.resources | nindent 10 }}
        livenessProbe:
          tcpSocket:
            port: otlp
          initialDelaySeconds: 60
          periodSeconds: 60
        ports:
        - containerPort: 21890
          name: otlp
        volumeMounts:
        - name: data-prepper-pipelines
          mountPath: /usr/share/data-prepper/pipelines/pipelines.yaml
          subPath: pipelines.yaml
        - name: data-prepper-config
          mountPath: /usr/share/data-prepper/data-prepper-config.yaml
          subPath: data-prepper-config.yaml
        - name: data-prepper-config
          mountPath: /usr/share/data-prepper/otel-span-ism-policy.json
          subPath: otel-span-ism-policy.json
        - name: data-prepper-config
          mountPath: /usr/share/data-prepper/otel-span-index-template.json
          subPath: otel-span-index-template.json
        - name: certificates
          mountPath: /usr/share/data-prepper/root-ca.pem
          subPath: ca.crt
        - name: certificates
          mountPath: /usr/share/data-prepper/server.key
          subPath: tls.key
        - name: certificates
          mountPath: /usr/share/data-prepper/server.crt
          subPath: tls.crt
        env:
        - name: os_url
          value: {{ include "os_url" . }}
        - name: os_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: username
        - name: os_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: password
        - name: JAVA_OPTS
          value: "-Xms{{ .Values.data_prepper.heapSize }} -Xmx{{ .Values.data_prepper.heapSize }} \
                  {{ .Values.opensearch.additionalJvmParams }}"
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh","-c",'/init/check_os.sh']
        env:
        - name: os_url
          value: {{ include "os_url" . }}
        - name: os_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: username
        - name: os_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: password
        volumeMounts:
        - name: certificates
          mountPath: /ssl/root-ca.pem
          subPath: ca.crt
        - name: init
          mountPath: "/init"
      volumes:
      - name: data-prepper-config
        configMap:
          name: {{ .Release.Name }}-data-prepper
      - name: data-prepper-pipelines
        secret:
          secretName: {{ .Release.Name }}-data-prepper
      - name: init
        configMap:
          name: {{ .Release.Name }}-init
          defaultMode: 0755
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-opensearch-certificates
{{- end }}
