{{- if .Values.opensearch.inCluster }}
{{ range $dataId := until (.Values.data.replicas | int) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-data-{{ $dataId }}
  labels: {{ include "logging.labels" $ | indent 4 }}
spec:
  ports:
    - port: 9300
      name: transport
    - port: 9200
      name: http
  selector: {{ include "logging.selectorLabels" $ | indent 4 }}
    {{- if $.Values.opensearch.singleNode }}
    type: single
    {{- else }}
    statefulset.kubernetes.io/pod-name: {{ $.Release.Name }}-data-{{ $dataId }}
    type: data
    {{- end }}
{{- end }}
{{- end }}