{{- if .Values.opensearch.externalOpensearch.disabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-index-templates
  labels: {{ include "logging.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-9"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- with .Values.additionalJobAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 10
  template:
    metadata:
      {{- with .Values.additionalJobPodAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{ include "logging.selectorLabels" . | indent 8 }}
        type: os-index-template
        {{- with .Values.additionalJobPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh","-c",'/init/check_os.sh']
        env:
          - name: os_url
            value: {{ include "os_url" . }}
          - name: os_user
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-opensearch-credentials-admin
                key: username
          - name: os_pass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-opensearch-credentials-admin
                key: password
        volumeMounts:
        - name: certificates
          mountPath: /ssl/root-ca.pem
          subPath: ca.crt
        - name: init
          mountPath: "/init"
      containers:
      - name: main
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.opensearch.imagePullPolicy }}
        command: ["sh", "-c", "/templates/templates.sh"]
        env:
          - name: os_url
            value: {{ include "os_url" . }}
          - name: os_cacert_file
            value: /etc/ssl/certs/open_search_ca.crt
          - name: os_user
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-opensearch-credentials-admin
                key: username
          - name: os_pass
            valueFrom:
              secretKeyRef:
                name: {{ .Release.Name }}-opensearch-credentials-admin
                key: password
          - name: os_data_nodes
            value: "{{ .Values.data.replicas }}"
        volumeMounts:
        - name: templates
          mountPath: /templates
        - name: certificates
          mountPath: /etc/ssl/certs/open_search_ca.crt
          subPath: ca.crt
          readOnly: true
      volumes:
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-opensearch-certificates
      - name: init
        configMap:
          name: {{ .Release.Name }}-init
          defaultMode: 0755
      - name: templates
        configMap:
          name: {{ .Release.Name }}-index-templates
          defaultMode: 0755
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-opensearch-certificates
          defaultMode: 0444
{{- end }}
