{{- if .Values.opensearch.externalOpensearch.disabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name}}-securityadmin
  labels: {{ include "logging.labels" . | indent 4 }}
data:
  setup.sh: |-
    #!/bin/bash

    set -e

    echo "executing security admin job"
    echo "node $os_node"

    export JAVA_HOME=/usr/share/opensearch/jdk
    export PATH=$PATH:$JAVA_HOME/bin

    chmod +x /usr/share/opensearch/plugins/opensearch-security/tools/hash.sh
    chmod +x /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh

    os_pass_hash=`/usr/share/opensearch/plugins/opensearch-security/tools/hash.sh -env os_pass | tail -1`
    ki_pass_hash=`/usr/share/opensearch/plugins/opensearch-security/tools/hash.sh -env ki_pass | tail -1`
    ki_ro_pass_hash=`/usr/share/opensearch/plugins/opensearch-security/tools/hash.sh -env ki_ro_pass | tail -1`
    ki_dev_pass_hash=`/usr/share/opensearch/plugins/opensearch-security/tools/hash.sh -env ki_dev_pass | tail -1`

    cp /usr/share/opensearch/config/opensearch-security/internal_users.yml /tmp/internal_users.yml

    chmod +w /tmp/internal_users.yml

    sed -i -e "s|\$\$opensearch-PASSWORD_HASH|$os_pass_hash|" /tmp/internal_users.yml
    sed -i -e "s|\$\$opensearch-dashboards_PASSWORD_HASH|$ki_pass_hash|" /tmp/internal_users.yml
    sed -i -e "s|\$\$opensearch-dashboards_READONLY_PASSWORD_HASH|$ki_ro_pass_hash|" /tmp/internal_users.yml
    sed -i -e "s|\$\$opensearch-dashboards_DEVELOPER_PASSWORD_HASH|$ki_dev_pass_hash|" /tmp/internal_users.yml

    echo "##### checking configurations #####"
    /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh \
      -cacert /usr/share/opensearch/config/root-ca.pem \
      -cert /usr/share/opensearch/config/admin.pem \
      -key /usr/share/opensearch/config/admin-key.key \
      -cd /usr/share/opensearch/config/opensearch-security \
      -h $os_node -vc

    echo "##### setting up security configuration #####"

    /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh \
      -cacert /usr/share/opensearch/config/root-ca.pem \
      -cert /usr/share/opensearch/config/admin.pem \
      -key /usr/share/opensearch/config/admin-key.key \
      -cd /usr/share/opensearch/config/opensearch-security \
      -h $os_node -sniff -icl

    echo "##### setting up users configuration #####"
    /usr/share/opensearch/plugins/opensearch-security/tools/securityadmin.sh \
      -cacert /usr/share/opensearch/config/root-ca.pem \
      -cert /usr/share/opensearch/config/admin.pem \
      -key /usr/share/opensearch/config/admin-key.key \
      -f /tmp/internal_users.yml \
      -h $os_node -sniff -icl

{{- end }}
