{{- if .Values.opensearch.inCluster }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-securityadmin
  labels: {{ include "logging.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": "post-install,post-upgrade"
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": "before-hook-creation"
    {{- with .Values.additionalJobAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  backoffLimit: 10
  template:
    metadata:
      annotations:
        "sidecar.istio.io/inject": "false"
    spec:
      restartPolicy: OnFailure
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml . | nindent 6 }}
      {{- end }}
      initContainers:
      - name: init
        image: {{ include "init_container.image" . }}
        imagePullPolicy: {{ .Values.init_container.imagePullPolicy }}
        command: ["sh", "-c", "/init/check_host_port.sh $os_node 9300 && /init/init_os_node.sh -only-keys"]
        env:
          - name: os_node
            value: {{ printf "%s-data-%d.%s.svc.cluster.local" .Release.Name (sub (.Values.data.replicas | int) 1) .Release.Namespace}}
        volumeMounts:
        - mountPath: "/init"
          name: init
        - mountPath: "/shared"
          name: shared
        - name: certificates
          mountPath: /config/node-key.pem
          subPath: tls.key
        - name: certificates
          mountPath: /config/ofd-rest-key.pem
          subPath: tls.key
        - name: admin-certificate
          mountPath: /config/admin-key.pem
          subPath: tls.key
      containers:
      - name: main
        image: {{ .Values.opensearch.image }}:{{ .Values.opensearch.imageTag }}
        imagePullPolicy: {{ .Values.opensearch.imagePullPolicy }}
        command: ["sh", "-c", "/setup.sh"]
        env:
        - name: os_url
          value: {{ include "os_url" . }}
        - name: os_node
          value: {{ printf "%s-data-%d.%s.svc.cluster.local" .Release.Name (sub (.Values.data.replicas | int) 1) .Release.Namespace}}
        - name: os_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: username
        - name: os_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-credentials-admin
              key: password
        - name: ki_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dashboards-credentials-admin
              key: username
        - name: ki_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dashboards-credentials-admin
              key: password
        - name: ki_ro_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dashboards-credentials-readonly
              key: username
        - name: ki_ro_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dashboards-credentials-readonly
              key: password
        - name: ki_dev_user
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dashboards-credentials-developer
              key: username
        - name: ki_dev_pass
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-opensearch-dashboards-credentials-developer
              key: password
        volumeMounts:
        - name: setup
          mountPath: /setup.sh
          subPath: setup.sh
        - name: certificates
          mountPath: /usr/share/opensearch/config/node.pem
          subPath: tls.crt
        - name: certificates
          mountPath: /usr/share/opensearch/config/root-ca.pem
          subPath: ca.crt
        - name: admin-certificate
          mountPath: /usr/share/opensearch/config/admin.pem
          subPath: tls.crt
        - name: shared
          mountPath: /usr/share/opensearch/config/node-key.key
          subPath: node-key.key
        - name: shared
          mountPath: /usr/share/opensearch/config/ofd-rest-key.key
          subPath: ofd-rest-key.key
        - name: shared
          mountPath: /usr/share/opensearch/config/admin-key.key
          subPath: admin-key.key
        - name: securityconfig
          mountPath: /usr/share/opensearch/config/opensearch-security
      volumes:
      - name: certificates
        secret:
          secretName: {{ .Release.Name }}-opensearch-certificates
      - name: admin-certificate
        secret:
          secretName: {{ .Release.Name }}-opensearch-admin-certificate
      - name: securityconfig
        secret:
          secretName: {{ .Release.Name }}-securityconfig
          defaultMode: 0644
      - name: init
        configMap:
          name: {{ .Release.Name}}-init
          defaultMode: 0755
      - name: setup
        configMap:
          name: {{ .Release.Name}}-securityadmin
          defaultMode: 0755
      - name: shared
        emptyDir: {}
{{- end }}
