name: Release Kubernetes Logging Helm Chart

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
          
      - name: Helm Chart Releaser
        uses: helm/chart-releaser-action@v1.2.1
        env:
          CR_TOKEN: "${{ secrets.TOKEN }}"
        with:
          charts_dir: charts
          # The GitHub Pages URL to the charts repo (default: https://<owner>.github.io/<repo>)
          charts_repo_url: https://nickytd.github.io/kubernetes-logging-helm
